In [21]:
# Run some setup code for this notebook.
import sys, os
from joblib import Parallel, delayed
import random
import numpy as np
import matplotlib
from itertools import cycle

In [36]:
l=np.arange(12).reshape(4,3)
y=np.array([0,1,2,2])
print l
print ' -- '
print l[np.arange(4),y]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
 -- 
[ 0  4  8 11]
